# Generated by Django 3.1.2 on 2020-10-27 01:18

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='author',
            managers=[
                ('object_manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
