# Generated by Django 3.1.2 on 2020-11-19 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_auto_20201030_1846'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['title', 'date'], 'verbose_name': 'Libro', 'verbose_name_plural': 'Libros'},
        ),
    ]
