# Generated by Django 3.1.2 on 2020-11-19 21:28

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0002_auto_20201030_1846'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='loan',
            managers=[
                ('object_manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
