# Generated by Django 3.1.2 on 2020-11-19 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50, verbose_name='Name')),
                ('country', models.CharField(max_length=30, verbose_name='Country')),
                ('passport', models.CharField(max_length=50, verbose_name='Passport')),
                ('age', models.IntegerField()),
                ('alias', models.CharField(max_length=10, verbose_name='Alias')),
            ],
            options={
                'verbose_name': 'Person',
                'verbose_name_plural': 'Persons',
                'db_table': 'PersonModel',
            },
        ),
    ]
